all32:
	arm-linux-gnueabi-gcc -o App TestApp.c ApollonDriver.a
	#arm-linux-gnueabi-g++ -std=c++11 -o Node0 Node0.cpp ApollonDriverC++.a
	#arm-linux-gnueabi-g++ -std=c++11 -o Node1 Node1.cpp ApollonDriverC++.a
	#arm-linux-gnueabi-g++ -std=c++11 -o Node2 Node2.cpp ApollonDriverC++.a
	#arm-linux-gnueabi-gcc -o App1 TestApp1.c ApollonDriver.a
all64:
	aarch64-linux-gnu-gcc -o App TestApp.c ApollonDriver.a	
clean:
	rm -rf App

